# Use an official PHP runtime as parent
FROM php:${PHP_VERSION:-7.3}-fpm
WORKDIR /var/www/html

# Make Sure we are Up To Date
RUN apt update \
	&& apt install -y nginx \
    wget \
    && rm -f /etc/nginx/sites-enabled/default \
    && docker-php-ext-install mbstring pdo_mysql

# Copy HTML File
ADD ./etc/api.prionplatform.com.conf /etc/nginx/conf.d/api.prionplatform.conf

EXPOSE 9000
CMD ["php-fpm", "-F"]

# Start nginx
CMD ["nginx", "-g", "daemon off;"]

RUN composer install --no-interaction --prefer-dist \
	&& composer dump-autoload

RUN php artisan optimize \
	&& php artisan route:clear \
	&& php artisan config:clear