version: '3'
services:

    # Prion Platform API Nginx
    api.prionplatform.nginx:
        build:
            context: ../..
            dockerfile: ./deploy/dev/dockerfile-nginx
        container_name: api.prionplatform.nginx
        environment:
            APP_URL: ${APP_URL:-https://api-dev.prionplatform.test}
            LOG_CHANNEL: 'stderr'
            VIRTUAL_HOST: "api-dev.prionplatform.test"
            VIRTUAL_PORT: "3116"
        ports:
            - 3116:80

    # Prion Platform API PHP-FPM
    api-dev.prionplatform:
        container_name: api-dev.prionplatform
        build:
            context: ../..
            dockerfile: ./deploy/dev/dockerfile
        environment:
            APP_URL: ${APP_URL:-https://api-dev.prionplatform.test}
            DB_HOST: "mariadb"
            LOG_CHANNEL: 'stderr'
            VIRTUAL_HOST: "api.prionplatform.test"
        external_links:
            - "redis:redis"
            - "mariadb:mariadb"
        ports:
            - 9000:9000
        restart: on-failure

# Networks
networks:
    default:
        external:
            name: nginx-proxy