# Use an official PHP runtime as parent
FROM webdevops/php-nginx:7.3

ENV WEB_DOCUMENT_ROOT "/var/www/html/public"
WORKDIR /var/www/html

# Make Sure we are Up To Date
RUN apt update \
	&& apt install -y nano \
    wget \
    git \
    zip \
    unzip \
    && rm -f /etc/nginx/sites-enabled/default \
    && docker-php-ext-install mbstring pdo_mysql

# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('SHA384', 'composer-setup.php') === ${COMPOSER_HASH:-'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1'}) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

# Copy HTML File
#ADD ./deploy/dev/etc/api.prionplatform.com.conf /etc/nginx/sites-enabled/api.prionplatform.conf
ADD ./deploy/dev/etc/nginx.conf /etc/nginx/nginx.conf

# Copy Repo into Image
COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html

# Customize PHP
ENV PHP_DISMOD=ioncube,mongodb
ENV fpm.pool.access.log "/dev/null"
ENV fpm.pool.decorate_workers_output "no"

RUN cd /var/www/html \
    && composer install --no-interaction --prefer-dist