version: '3'
services:

    # Prion Platform API
    api.prionplatform:
        container_name: api.prionplatform
        build:
            context: ../..
            dockerfile: ./deploy/dev/dockerfile
        environment:
            APP_URL: ${APP_URL:-https://api.prionplatform.test}
            DB_HOST: "mariadb"
            LOG_CHANNEL: 'stderr'
            VIRTUAL_HOST: "api.prionplatform.test"
            VIRTUAL_PORT: "3106"
        expose:
            - 3106
        external_links:
            - "redis:redis"
            - "mariadb:mariadb"
        ports:
            - 3106:3106
        restart: on-failure

# Networks
networks:
    default:
        external:
            name: nginx-proxy