# Use an official PHP runtime as parent
FROM webdevops/php-nginx:7.3

ENV WEB_DOCUMENT_ROOT "/var/www/html/public"
WORKDIR /var/www/html

# Make Sure we are Up To Date
RUN apt update \
	&& apt install -y nano \
    wget \
    git \
    zip \
    unzip \
    && rm -f /etc/nginx/sites-enabled/default \
    && docker-php-ext-install mbstring pdo_mysql

# Copy HTML File
ADD ./deploy/local/etc/api.prionplatform.com.conf /etc/nginx/sites-enabled/api.prionplatform.conf

# Customize PHP
ENV PHP_DISMOD=ioncube,mongodb
ENV fpm.pool.access.log "/dev/null"
ENV fpm.pool.decorate_workers_output "no"