# Use an official PHP runtime as parent
FROM php:${PHP_VERSION:-7.3}-fpm

ENV WEB_DOCUMENT_ROOT "/var/www/html/public"

WORKDIR /var/www/html

# Make Sure we are Up To Date
RUN apt update \
	&& apt install -y nano \
    wget \
    git \
    zip \
    unzip \
    && rm -f /etc/nginx/sites-enabled/default \
    && docker-php-ext-install mbstring pdo_mysql

# Customize PHP
ENV PHP_DISMOD=ioncube,mongodb
ENV fpm.pool.access.log "/dev/null"
ENV fpm.pool.decorate_workers_output "no"