version: '3'
services:

    # Bisnow.com Application
    api.prionplatform:
        container_name: api.prionplatform
        build:
            context: ./
            dockerfile: prod.dockerfile
        environment:
            API_URL: ${APP_URL:-https://api.prionplatform.com}
            DB_POST: 3306
            DB_HOST: localhost
        expose:
            - 3101
        ports:
            - 3101:3101
        restart: on-failure

# Networks
networks:
    default:
        external:
            name: nginx-proxy