version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      #- printenv
      - echo -n "$CODEBUILD_LOG_PATH" > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
      # App config is copied to S3 using "docker/push-config-s3.sh" script
      - echo "Retrieve app config from Amazon S3 template bucket ($TEMPLATE_BUCKET)..."
      - aws s3 cp "s3://$TEMPLATE_BUCKET/config/.env" laravel/.env
      - echo APP_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION >> laravel/.env
  build:
    commands:
      - php --version
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --tag "$(cat /tmp/build_tag.out)" .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push "$(cat /tmp/build_tag.out)"
