version: '3'
services:

    # Bisnow.com Application
    api.prionplatform:
        container_name: api.prionplatform
        build:
            context: ./
            dockerfile: dockerfile
        environment:
            API_URL: ${APP_URL:-https://api.prionplatform.com}
            DB_POST: 3306
            DB_HOST: localhost
        expose:
            - 80
        ports:
            - 80:80
        restart: on-failure