version: 0.2

phases:
  install:
    runtime-versions:
      php: $AWS_PHP_VERSION
    commands:
      - |
        #Install composer
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php -r "if (hash_file('SHA384', 'composer-setup.php') === "$COMPOSER_HASH") { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        php composer-setup.php ;
        php -r "unlink('composer-setup.php');" ;
        mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)

  build:
    commands:
      - php --version
      - echo Build started on `date`
      - composer install --no-interaction --prefer-dist

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'