version: '3'
services:

    # Prion Platform API
    api.prionplatform:
        container_name: api.prionplatform
        build:
            context: ./
            dockerfile: dockerfile
            cache_from: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_PREFIX}:${IMAGE_TAG}
        environment:
            API_URL: ${APP_URL:-https://api.prionplatform.com}
            DB_POST: 3306
            DB_HOST: localhost
        expose:
            - 80
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_PREFIX}:${IMAGE_TAG}
        ports:
            - 80:80
        restart: on-failure