# Use an official PHP runtime as parent
FROM php:${PHP_VERSION:-7.3}-fpm
WORKDIR /var/www/html

# Make Sure we are Up To Date
RUN apt update \
	&& apt install -y nginx \
    wget \
    git \
    zip \
    unzip \
    && rm -f /etc/nginx/sites-enabled/default \
    && docker-php-ext-install mbstring pdo_mysql

# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('SHA384', 'composer-setup.php') === ${COMPOSER_HASH:-'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1'}) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

# Copy HTML File
ADD ./deploy/production/etc/api.prionplatform.com.conf /etc/nginx/conf.d/api.prionplatform.conf

# Copy Repo into Image
COPY . .

EXPOSE 9000
CMD ["php-fpm", "-F"]

# Start nginx
CMD ["nginx", "-g", "daemon off;"]

RUN composer install --no-interaction --prefer-dist \
	&& composer dump-autoload

RUN php artisan optimize \
	&& php artisan route:cache \
	&& php artisan config:cache